// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxH_RLFECrRPQuBobLf3YLPh3qcmflso',
    appId: '1:179107877818:web:6934d2e29b644508758383',
    messagingSenderId: '179107877818',
    projectId: 'notestaker',
    authDomain: 'notestaker-1bdbd.firebaseapp.com',
    storageBucket: 'notestaker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzW__5lYx_vyMmoSS0Z02sobyc4_UXXy8',
    appId: '1:179107877818:android:2e29bc47e9d2e012758383',
    messagingSenderId: '179107877818',
    projectId: 'notestaker',
    storageBucket: 'notestaker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6QwdPOJ524K70c07N0Y8kBO-SKmgHml8',
    appId: '1:179107877818:ios:a72d31bda04c23ca758383',
    messagingSenderId: '179107877818',
    projectId: 'notestaker',
    storageBucket: 'notestaker.appspot.com',
    iosClientId: '179107877818-rrva4bkfhn9p7iq9kn1vn1v567i0komd.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
