// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxH_RLFECrRPQuBobLf3YLPh3qcmflso',
    appId: '1:179107877818:web:6934d2e29b644508758383',
    messagingSenderId: '179107877818',
    projectId: 'notestaker',
    authDomain: 'notestaker-1bdbd.firebaseapp.com',
    storageBucket: 'notestaker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzW__5lYx_vyMmoSS0Z02sobyc4_UXXy8',
    appId: '1:179107877818:android:a3b849e508be6513758383',
    messagingSenderId: '179107877818',
    projectId: 'notestaker',
    storageBucket: 'notestaker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6QwdPOJ524K70c07N0Y8kBO-SKmgHml8',
    appId: '1:179107877818:ios:4d7c28c6bbb6401a758383',
    messagingSenderId: '179107877818',
    projectId: 'notestaker',
    storageBucket: 'notestaker.appspot.com',
    iosClientId: '179107877818-uqg7eu6m9nv7ujqcvsq0fl3kmt4k6e9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.forms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6QwdPOJ524K70c07N0Y8kBO-SKmgHml8',
    appId: '1:179107877818:ios:479040ccbb3544b1758383',
    messagingSenderId: '179107877818',
    projectId: 'notestaker',
    storageBucket: 'notestaker.appspot.com',
    iosClientId: '179107877818-t9nifmuaesr1kqgp70q9jeu5tmona1hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.forms.RunnerTests',
  );
}
